# Copyright (C) 2018 Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

# Wazuh master StatefulSet

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-manager-master
  namespace: wazuh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-manager
      node-type: master
  serviceName: wazuh-cluster
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: wazuh-manager
        node-type: master
      name: wazuh-manager-master
    spec:
      volumes:
        - name: config
          configMap:
            name: wazuh-manager-master-conf
        - name: filebeat
          configMap:
            name: wazuh-filebeat-conf
        - name: wazuh-authd-pass
          secret:
            secretName: wazuh-authd-pass
      containers:
        - name: wazuh-manager
          image: 'wazuh/wazuh-odfe:4.0.0_1.10.1'
          resources:
            requests:
              cpu: 2
              memory: 1024Mi
            limits:
              cpu: 2
              memory: 2048Mi
          volumeMounts:
            - name: config
              mountPath: /wazuh-config-mount/etc/ossec.conf
              subPath: ossec.conf
              readOnly: true
            - name: wazuh-authd-pass
              mountPath: /wazuh-config-mount/etc/authd.pass
              subPath: authd.pass
              readOnly: true
            - name: wazuh-manager-api-configuration
              mountPath: /var/ossec/api/configuration
            - name: wazuh-manager-etc
              mountPath: /var/ossec/etc
            - name: wazuh-manager-logs
              mountPath: /var/ossec/logs
            - name: wazuh-manager-queue
              mountPath: /var/ossec/queue
            - name: wazuh-manager-var-multigroups
              mountPath: /var/ossec/var/multigroups
            - name: wazuh-manager-integrations
              mountPath: /var/ossec/integrations
            - name: wazuh-manager-active-response
              mountPath: /var/ossec/active-response/bin
            - name: wazuh-manager-agentless
              mountPath: /var/ossec/agentless
            - name: wazuh-manager-wodles
              mountPath: /var/ossec/wodles
            - name: wazuh-manager-filebeat-etc
              mountPath: /etc/filebeat
            - name: wazuh-manager-filebeat-var
              mountPath: /var/lib/filebeat
          ports:
            - containerPort: 1515
              name: registration
            - containerPort: 1514
              name: events
            - containerPort: 55000
              name: api
          env:
            - name: ELASTICSEARCH_URL
              value: 'https://elasticsearch:9200'
            - name: ELASTIC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: elastic-cred
                  key: username
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elastic-cred
                  key: password
            - name: FILEBEAT_SSL_VERIFICATION_MODE
              value: 'none'
            - name: API_USERNAME
              valueFrom:
                secretKeyRef:
                  name: wazuh-api-cred
                  key: username
            - name: API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wazuh-api-cred
                  key: password
            - name: WAZUH_CLUSTER_KEY
              valueFrom:
                secretKeyRef:
                  name: wazuh-cluster-key
                  key: key
  volumeClaimTemplates:
    - metadata:
        name: wazuh-manager-api-configuration
        namespace: wazuh
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Mi
    - metadata:
        name: wazuh-manager-etc
        namespace: wazuh
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Mi
    - metadata:
        name: wazuh-manager-logs
        namespace: wazuh
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
    - metadata:
        name: wazuh-manager-queue
        namespace: wazuh
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Mi
    - metadata:
        name: wazuh-manager-var-multigroups
        namespace: wazuh
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Mi
    - metadata:
        name: wazuh-manager-integrations
        namespace: wazuh
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Mi
    - metadata:
        name: wazuh-manager-active-response
        namespace: wazuh
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Mi
    - metadata:
        name: wazuh-manager-agentless
        namespace: wazuh
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Mi
    - metadata:
        name: wazuh-manager-wodles
        namespace: wazuh
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Mi
    - metadata:
        name: wazuh-manager-filebeat-etc
        namespace: wazuh
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Mi
    - metadata:
        name: wazuh-manager-filebeat-var
        namespace: wazuh
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 200Mi
