# Copyright (C) 2018 Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

# Wazuh worker conf

apiVersion: v1
kind: ConfigMap
metadata:
  name: wazuh-filebeat-conf
  namespace: wazuh
data:
  filebeat.yml: |-
    # Wazuh - Filebeat configuration file
    filebeat.modules:
      - module: wazuh
        alerts:
          enabled: true
        archives:
          enabled: false

    setup.template.json.enabled: true
    setup.template.json.path: '/etc/filebeat/wazuh-template.json'
    setup.template.json.name: 'wazuh'
    setup.template.overwrite: true
    setup.ilm.enabled: false
    output.elasticsearch:
      hosts: ['https://elasticsearch:9200']
      username: admin
      password: admin
      ssl.verification_mode: none
      #ssl.certificate_authorities:
      #ssl.certificate:
      #ssl.key:
