# Copyright (C) 2018 Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

# Elasticsearch StatefulSet: Single node.

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-elasticsearch
  namespace: wazuh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-elasticsearch
  serviceName: wazuh-elasticsearch
  template:
    metadata:
      labels:
        app: wazuh-elasticsearch
      name: wazuh-elasticsearch
    spec:
      containers:
        - name: wazuh-elasticsearch
          image: 'amazon/opendistro-for-elasticsearch:1.10.1'
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1
              memory: 2Gi
          env:
            - name: ES_JAVA_OPTS
              value: '-Xms1024m -Xmx1024m'
            - name: node.name
              value: es01
            - name: cluster.name
              value: wazuh
            - name: network.host
              value: 0.0.0.0
            - name: discovery.type
              value: single-node
          volumeMounts:
            - name: wazuh-elasticsearch
              mountPath: /usr/share/elasticsearch/data
          ports:
            - containerPort: 9200
              name: es-rest
            - containerPort: 9300
              name: es-nodes
  volumeClaimTemplates:
    - metadata:
        name: wazuh-elasticsearch
        namespace: wazuh
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
